# Generated by Django 4.0.4 on 2022-06-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('overview', models.CharField(max_length=200)),
                ('poster', models.ImageField(upload_to='')),
                ('vote_average', models.IntegerField()),
                ('vote_count', models.IntegerField()),
            ],
        ),
    ]
