# Generated by Django 4.0.4 on 2022-06-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='image', upload_to='images/'),
        ),
    ]
